###########################################

# static params setting

###########################################
test: True
env_type: 'robot_nav'
robot_type: 'diff'
env_num: 1
agent_num_per_env: 1
batch_num_per_env: 1
env_id: 0 # if you set env_num > 1, the env_id will automatically increase when creating envs.

env_name: 'image_ped_circle'
cfg_name: 'image_ped_circle'
cfg_type: 'yaml'

control_hz: 0.25
time_max: 160
robot_radius: 0.5
ped_leg_radius: 0.1
ped_safety_space: 0.4
laser_max: 10.0
laser_norm: false
laser_shadow: false

image_batch: 1
image_size: [48, 48]
ped_image_size: [48, 48]
state_batch : 1
state_dim : 5
state_normalize: false
laser_batch : 1
act_dim: 2 # 2: v,w ; 3: v,w,v_y (for omni robot) 4: v,w,v_y,beep
discrete_action: False
discrete_actions: [
  [0.0, -0.9], [0.0, -0.8], [0.0, -0.7], [0.0, -0.6], [0.0, -0.5], [0.0, -0.4], [0.0, -0.3], [0.0, -0.2], [0.0, -0.1], [0.0, 0.0], [0.0, 0.1], [0.0, 0.2], [0.0, 0.3], [0.0, 0.4], [0.0, 0.5], [0.0, 0.6], [0.0, 0.7], [0.0, 0.8], [0.0, 0.9],
  [0.1, -0.9], [0.1, -0.8], [0.1, -0.7], [0.1, -0.6], [0.1, -0.5], [0.1, -0.4], [0.1, -0.3], [0.1, -0.2], [0.1, -0.1], [0.1, 0.0], [0.1, 0.1], [0.1, 0.2], [0.1, 0.3], [0.1, 0.4], [0.1, 0.5], [0.1, 0.6], [0.1, 0.7], [0.1, 0.8], [0.1, 0.9],
  [0.2, -0.9], [0.2, -0.8], [0.2, -0.7], [0.2, -0.6], [0.2, -0.5], [0.2, -0.4], [0.2, -0.3], [0.2, -0.2], [0.2, -0.1], [0.2, 0.0], [0.2, 0.1], [0.2, 0.2], [0.2, 0.3], [0.2, 0.4], [0.2, 0.5], [0.2, 0.6], [0.2, 0.7], [0.2, 0.8], [0.2, 0.9],
  [0.3, -0.9], [0.3, -0.8], [0.3, -0.7], [0.3, -0.6], [0.3, -0.5], [0.3, -0.4], [0.3, -0.3], [0.3, -0.2], [0.3, -0.1], [0.3, 0.0], [0.3, 0.1], [0.3, 0.2], [0.3, 0.3], [0.3, 0.4], [0.3, 0.5], [0.3, 0.6], [0.3, 0.7], [0.3, 0.8], [0.3, 0.9],
  [0.4, -0.9], [0.4, -0.8], [0.4, -0.7], [0.4, -0.6], [0.4, -0.5], [0.4, -0.4], [0.4, -0.3], [0.4, -0.2], [0.4, -0.1], [0.4, 0.0], [0.4, 0.1], [0.4, 0.2], [0.4, 0.3], [0.4, 0.4], [0.4, 0.5], [0.4, 0.6], [0.4, 0.7], [0.4, 0.8], [0.4, 0.9],
  [0.5, -0.9], [0.5, -0.8], [0.5, -0.7], [0.5, -0.6], [0.5, -0.5], [0.5, -0.4], [0.5, -0.3], [0.5, -0.2], [0.5, -0.1], [0.5, 0.0], [0.5, 0.1], [0.5, 0.2], [0.5, 0.3], [0.5, 0.4], [0.5, 0.5], [0.5, 0.6], [0.5, 0.7], [0.5, 0.8], [0.5, 0.9],
  [0.6, -0.9], [0.6, -0.8], [0.6, -0.7], [0.6, -0.6], [0.6, -0.5], [0.6, -0.4], [0.6, -0.3], [0.6, -0.2], [0.6, -0.1], [0.6, 0.0], [0.6, 0.1], [0.6, 0.2], [0.6, 0.3], [0.6, 0.4], [0.6, 0.5], [0.6, 0.6], [0.6, 0.7], [0.6, 0.8], [0.6, 0.9],
  [0.7, -0.9], [0.7, -0.8], [0.7, -0.7], [0.7, -0.6], [0.7, -0.5], [0.7, -0.4], [0.7, -0.3], [0.7, -0.2], [0.7, -0.1], [0.7, 0.0], [0.7, 0.1], [0.7, 0.2], [0.7, 0.3], [0.7, 0.4], [0.7, 0.5], [0.7, 0.6], [0.7, 0.7], [0.7, 0.8], [0.7, 0.9],
  [0.8, -0.9], [0.8, -0.8], [0.8, -0.7], [0.8, -0.6], [0.8, -0.5], [0.8, -0.4], [0.8, -0.3], [0.8, -0.2], [0.8, -0.1], [0.8, 0.0], [0.8, 0.1], [0.8, 0.2], [0.8, 0.3], [0.8, 0.4], [0.8, 0.5], [0.8, 0.6], [0.8, 0.7], [0.8, 0.8], [0.8, 0.9],
  [0.9, -0.9], [0.9, -0.8], [0.9, -0.7], [0.9, -0.6], [0.9, -0.5], [0.9, -0.4], [0.9, -0.3], [0.9, -0.2], [0.9, -0.1], [0.9, 0.0], [0.9, 0.1], [0.9, 0.2], [0.9, 0.3], [0.9, 0.4], [0.9, 0.5], [0.9, 0.6], [0.9, 0.7], [0.9, 0.8], [0.9, 0.9],
  [1.0, -0.9], [1.0, -0.8], [1.0, -0.7], [1.0, -0.6], [1.0, -0.5], [1.0, -0.4], [1.0, -0.3], [1.0, -0.2], [1.0, -0.1], [1.0, 0.0], [1.0, 0.1], [1.0, 0.2], [1.0, 0.3], [1.0, 0.4], [1.0, 0.5], [1.0, 0.6], [1.0, 0.7], [1.0, 0.8], [1.0, 0.9],
  ]
continuous_actions: [ [0, 1.0] , [-0.9, 0.9], [-0.6, 0.6]]
### speed_limiter, refer to real turtlebot2
speed_limiter_v:
  has_velocity_limits: True
  has_acceleration_limits: True
  has_jerk_limits: False
  min_velocity: 0
  max_velocity: 1.0
  min_acceleration: -1.6
  max_acceleration: 5
  min_jerk: 0
  max_jerk: 0
speed_limiter_w:
  has_velocity_limits: True
  has_acceleration_limits: True
  has_jerk_limits: False
  min_velocity: -0.9
  max_velocity: 0.9
  min_acceleration: -0.6
  max_acceleration: 2
  min_jerk: 0
  max_jerk: 0


circle_ranges: [1.8, 3.2] # only used in circle env

max_ped: 10
ped_vec_dim: 7
ped_image_r: 0.3 # the radius of pedestrians in ped_image, paper:

###########################################
# ROS CPP NODE PARAMS
###########################################
show_gui: True
sleep_t: 0.
window_height: 500
show_image_height: 125
is_draw_step: true
step_draw: 3
use_laser: true
# 360 view angle
#range_total: 1920
#view_angle_begin: -3.1415
#view_angle_end: 3.1415
#view_min_dist: -10
#view_max_dist: 10.0

# 180 view angle
range_total: 960
view_angle_begin: -1.570795
view_angle_end: 1.570795
view_min_dist: 0
view_max_dist: 10.0

beep_r: 1.0
ped_ca_p: 1.0
relation_ped_robo: 0

#########################################
bag_record_output_name: "test1.bag"
bag_record_epochs: 5

init_pose_bag_episodes: 600
init_pose_bag_name: "10obs_static_baseline.bag"
##########################################

# wrapper setting
# NOTE: wrapper sequentially ！！！
# for excemple,
# wrapper: [A, B] means :
#     env = B(A(env))

###########################################

wrapper: [
  #'BagRecordWrapper',
  'VelActionWrapper',
  'TimeLimitWrapper',
  'SensorsPaperRewardWrapper',
  'InfoLogWrapper',
  'MultiRobotCleanWrapper',
  "TestEpisodeWrapper",
  #  'StatePedVectorWrapper',
  'StateBatchWrapper', # statebatch wrapper一般放在最后面
  'ObsLaserStateTmp',
  "BarnDataSetWrapper",
  "NeverStopWrapper", # 训练时候，不停的跑，这个要放在最后，因为reset对你之前的状态进行了修改


]


###########################################

# agents setting

###########################################

global_map:
  resolution: 0.2
  map_file: room_54_144.png
view_map:
  resolution: 0.015
  width: 6
  height: 6
robot:
  total: 1
  robot_type: ['diff', 'diff', 'omni']
  shape: ['rectangle', 'rectangle', 'circle','sweep', 'range', 'range', 'rectangle','circle','circle','circle','circle','circle','circle','circle','circle']
### example shape:
#  'sweep' [-0.35,0.35,-0.45,0.45]
#  'L' [0,0.55,0,0.25,0,0]
#  'rectangle [-0.35,0.35,-0.45,0.45]
#  'circle' [0, 0, 0.17]
  size: [ [-0.44, 0, -0.22, 0.22], [-0.3, 0.3, -0.25, 0.25], [0, 0, 0.17], [0.15, 0.4],[-0.35,0.35,-0.45,0.45, 0, 0],[0.15, 0.45], [-0.55,0.55,-0.25,0.25], [0, 0, 0.17], [0, 0, 0.17], [0, 0, 0.17], [0, 0, 0.17], [0, 0, 0.17],[0, 0, 0.17], [0, 0, 0.17], [0, 0, 0.17]]
  begin_poses_type: ['fix', 'range_circle', 'range_circle', 'range_circle', 'range','range', 'range', 'range', 'range','range', 'range', 'range', 'range']
  begin_poses: [[5.5, 8.0, 1.5708],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5]]
  target_poses_type: ['fix', 'range_circle', 'range_circle', 'range_circle', 'range_view','range_view', 'range_view', 'range_view', 'range_view','range_view', 'range_view', 'range_view', 'range_view']
  target_poses: [[5.5, 24.0, 1.5708], [5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5]]
  # sensor_cfgs: [[0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0], [0.14, 0]]
object:
  total: 10
  shape: ['circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle','circle',  'rectangle']
  size_range: [[0.3, 0.6],[-0.45,0.45,-0.25,0.25],[0.4, 0.4],[-0.25,0.25,-0.25,0.25],[0.3, 0.6],[-0.25,0.25,-0.25,0.25],[0.3, 0.8],[-0.15,0.15,-0.15,0.15],[0.6, 0.9],[-0.15,0.15,-0.15,0.15],[0.3, 0.3],[-0.15,0.15,-0.15,0.15],[0.3, 0.3],[-0.25,0.25,-0.25,0.25],[0.4, 0.4],[-0.25,0.25,-0.25,0.25],[0.3, 0.3],[-0.25,0.25,-0.25,0.25],[0.3, 0.3],[-0.45,0.45,-0.25,0.25],[0.3, 0.3],[-0.45,0.45,-0.15,0.15],[0.3, 0.3],[-0.15,0.15,-0.15,0.15]]
  poses_type: ['range',  'range','range',  'range','range',  'range','range',  'range','range',  'range','range',  'range','range',  'range','range',  'range','range',  'range','range',  'range','range',  'range','range',  'range']
  poses: [[1.5, 9.5, 1.5, 9.5], [1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5],[2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5]]

ped_sim:
  total: 0
  type: 'pedscene' # you can choose pedscene, rvoscene, ervoscene
  max_speed: [0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5]
  shape: ['leg','leg','leg','leg','leg','leg','leg','leg','leg','leg','leg','leg','leg','leg','leg','leg','circle','circle','circle','circle','circle']
  size: [[0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1], [0, 0.1, 0.1],[0, 0, 0.17]]
  begin_poses_type: ['range','range','range','range','range','range_circle','range_circle','range_circle','range_circle','range_circle','range_circle','range_circle','range_circle', 'range', 'range', 'range', 'range','range', 'range', 'range', 'range']
  begin_poses: [[2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5], [5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5], [1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5], [2.5, 8.5, 2.5, 8.5]]
  target_poses_type: ['range','range','range','range','range','range_circle','range_circle','range_circle','range_circle','range_circle','range_circle','range_circle','range_circle','range_view', 'range_view', 'range_view', 'range_view','range_view', 'range_view', 'range_view', 'range_view']
  target_poses: [[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5], [5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[5.5,5.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5], [2.5, 8.5, 2.5, 8.5],[1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5], [1.5, 9.5, 1.5, 9.5],[1.5, 9.5, 1.5, 9.5], [2.5, 8.5, 2.5, 8.5]]
  go_back: "random" # yes: all ped go back after hit the goal again and again, "random": random choose, "no": none of ped
  ignore_obstacle: True
target_min_dist: 3.0 # min distance between start point to target point.

node_id: 0

Agent:
  standardization: True
  T: 10 # softmax with tempreture to encorage exploration
  entropy_coef: 0.02  # entropy coefficient for regurization (default 0.2)
  beta: 1.0  # beta for balancing l1 and l2 loss
  clip_grad_norm: 1.0 # gradient norm clipping (default 0.5)
  learning_rate: 2.5e-4
  use_cuda: True
  training: False
  input_size: 965
  output_size: 209
  reward_size: 6
  tb_logdir: "./output/model/tfboard"

Training:
  gamma: 0.99 # gamma for discounted rewards (default 0.99)
  lam: 0.95 # lambda for gae (default 0.95)
  use_gae: True
  num_worker: 16
  sample_size: 8
  num_step: 5 # number of gae steps (default 5)
  enve_start: 100000  # minimum number of naive traning before envelope
  update_target_critic: 10000 # the number of steps to update target critic

output_path: './output/model'